title: Pantheon Insights
author: Dimitri Zabelin
email: dzabelin@pantheoninsights.com
description: >- # this means to ignore newlines until "baseurl:"
  Pantheon Insights is a boutique consulting firm specializing in the intersection of 
  geopolitics, markets, and economies. Our philosophical foundation draws on the ancient symbolism 
  of the Pantheon: A collective set of principles that guides people and institutions in 
  times of uncertainty. We work closely with clients across the world to provide bespoke, 
  strategic insights for navigating and prospering in the dynamic terrain of 21st-century geopolitics.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "panethoninsights.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ZabelinDimitri
linkedin_username: Dimitri-Zabelin

# Build settings
theme: minima
plugins:
  - jekyll-feed

page_paths:
  - title: About
    url: /about/
    order: 1
  - title: Consulting Services
    url: /services/
    order: 2
  - title: Daily Insights
    url: /insights/
    order: 3
  - title: Contact
    url: /contact/
    order: 4

sass:
  sass_dir: _sass