title: Pantheon Insights
author: Dimitri Zabelin
email: dzabelin@pantheoninsights.com
description: >- # this means to ignore newlines until "baseurl:"
  Pantheon Insights translates geopolitical trends into actionable insights,
  helping businesses and investors align their strategies with a shifting world
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "panethoninsights.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: https://panetheoninsights.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://panetheoninsights.com/  # the base hostname and protocol for your site, e.g. http://example.com


twitter_username: ZabelinDimitri
linkedin_username: Dimitri-Zabelin

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass